version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: tms-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tm-spring
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasknet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tm-spring" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: taskmanager-spring:latest
    container_name: tms-app
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tm-spring
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres


      # OPTIONAL: enable remote debug only when needed
#      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"

    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - tasknet
    restart: unless-stopped

volumes:
  pgdata:

networks:
  tasknet:
    driver: bridge
