# HTTP
quarkus.http.port=8081

#quarkus.http.auth.basic=true

# enable form auth
quarkus.http.auth.form.enabled=true
# your login page route
quarkus.http.auth.form.login-page=/login
# where Quarkus expects the login POST (if you use the built-in form flow)
quarkus.http.auth.form.post-location=/j_security_check
# field names if you use the built-in POST
quarkus.http.auth.form.username-parameter=j_username
quarkus.http.auth.form.password-parameter=j_password


# Require JWT on /api/**
quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated
quarkus.http.auth.permission.api.auth-mechanism=JWT

# Require FORM on everything else (your pages)
quarkus.http.auth.permission.web.paths=/*
quarkus.http.auth.permission.web.policy=authenticated
quarkus.http.auth.permission.web.methods=GET,POST
quarkus.http.auth.permission.web.auth-mechanism=FORM


#JWT best practices (SmallRye JWT)
#Set verify keys (PEM or JWKS) via mp.jwt.verify.publickey.location.
#Set signing key via smallrye.jwt.sign.key.location (don?t inline secrets in config).
#Consider mp.jwt.verify.audiences and smallrye.jwt.required.claims for stricter validation
quarkus.smallrye-jwt.enabled=true
# verify token
mp.jwt.verify.publickey.location=publicKey.pem
# sign token (file or keystore; avoid inlining)
smallrye.jwt.sign.key.location=privateKey.pem
# optional hardening
mp.jwt.verify.audiences=taskmanager
#smallrye.jwt.required.claims=sub,exp,iat,groups


# If you later use OIDC, you can control cookie flags:
# quarkus.oidc.authentication.cookie-same-site=strict
# quarkus.oidc.authentication.cookie-force-secure=true

# For general HTTP SameSite cookie config (see All config guide)
# quarkus.http.same-site-cookie.session.value=strict




quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/quarkus?options=-c%20TimeZone=Europe/Kyiv

quarkus.hibernate-orm.schema-management.strategy=drop-and-create

#quarkus.hibernate-orm.database.timezone=UTC
